// components/admin/mockData.js

export const MOCK_CAMPAIGNS = [
  {
    id: 1,
    title: "Johnson for Governor",
    candidate: "Marcus Johnson",
    office: "Governor",
    state: "Texas",
    party: "Democratic",
    website: "https://johnson2026.com",
    adminName: "Sarah Collins",
    adminEmail: "sarah@johnson2026.com",
    phone: "+1 512-555-0101",
    plan: "enterprise",
    status: "active",
    logo: null,
    created: "2025-11-03",
    nextBilling: "2026-04-03",
    mrr: 499,
    seats: 48,
    notes: "Key flagship client. Priority support.",
  },
  {
    id: 2,
    title: "Kim Senate Campaign",
    candidate: "Yuna Kim",
    office: "U.S. Senate",
    state: "California",
    party: "Democratic",
    website: "https://kimsenate.com",
    adminName: "Derek Moss",
    adminEmail: "derek@kimsenate.com",
    phone: "+1 415-555-0202",
    plan: "pro",
    status: "active",
    logo: null,
    created: "2025-12-14",
    nextBilling: "2026-04-14",
    mrr: 199,
    seats: 22,
  },
  {
    id: 3,
    title: "Rivera for Mayor",
    candidate: "Elena Rivera",
    office: "Mayor",
    state: "New York",
    party: "Independent",
    adminName: "Tom Obi",
    adminEmail: "tom@riverafornyc.com",
    phone: "+1 212-555-0303",
    plan: "starter",
    status: "suspended",
    logo: null,
    created: "2025-09-07",
    nextBilling: "—",
    mrr: 0,
    seats: 7,
    notes: "Suspended — failed payment 3/10/2026.",
  },
  {
    id: 4,
    title: "Patel District 12",
    candidate: "Rahul Patel",
    office: "City Council",
    state: "Illinois",
    party: "Republican",
    adminName: "Nadia Chen",
    adminEmail: "nadia@patel12.com",
    phone: "+1 773-555-0404",
    plan: "starter",
    status: "active",
    logo: null,
    created: "2026-01-19",
    nextBilling: "2026-04-19",
    mrr: 79,
    seats: 5,
  },
  {
    id: 5,
    title: "Foster for Congress",
    candidate: "Diane Foster",
    office: "U.S. House",
    state: "Florida",
    party: "Republican",
    adminName: "Luis Vega",
    adminEmail: "luis@foster4congress.com",
    phone: "+1 305-555-0505",
    plan: "pro",
    status: "pending",
    logo: null,
    created: "2026-03-01",
    nextBilling: "2026-04-01",
    mrr: 199,
    seats: 14,
  },
  {
    id: 6,
    title: "Williams for AG",
    candidate: "James Williams",
    office: "Attorney General",
    state: "Georgia",
    party: "Democratic",
    adminName: "Amy Frost",
    adminEmail: "amy@williamslag.com",
    phone: "+1 404-555-0606",
    plan: "enterprise",
    status: "active",
    logo: null,
    created: "2025-08-22",
    nextBilling: "2026-04-22",
    mrr: 499,
    seats: 61,
  },
];

export const MOCK_AUDIT_LOGS = [
  {
    id: 1,
    type: "created",
    user: "admin@campaignos.io",
    target: "Johnson for Governor",
    detail: "New campaign created with Enterprise plan",
    ts: "2026-03-24 14:32",
  },
  {
    id: 2,
    type: "suspended",
    user: "admin@campaignos.io",
    target: "Rivera for Mayor",
    detail: "Campaign suspended due to failed payment",
    ts: "2026-03-23 09:11",
  },
  {
    id: 3,
    type: "updated",
    user: "admin@campaignos.io",
    target: "Kim Senate Campaign",
    detail: "Upgraded plan from Starter → Pro",
    ts: "2026-03-22 16:45",
  },
  {
    id: 4,
    type: "login",
    user: "admin@campaignos.io",
    target: "Platform",
    detail: "Admin login from IP 196.29.4.12",
    ts: "2026-03-22 08:00",
  },
  {
    id: 5,
    type: "activated",
    user: "admin@campaignos.io",
    target: "Patel District 12",
    detail: "Campaign re-activated after payment",
    ts: "2026-03-21 11:22",
  },
  {
    id: 6,
    type: "created",
    user: "admin@campaignos.io",
    target: "Foster for Congress",
    detail: "New campaign created with Pro plan",
    ts: "2026-03-20 13:55",
  },
  {
    id: 7,
    type: "updated",
    user: "admin@campaignos.io",
    target: "Williams for AG",
    detail: "Admin contact email updated",
    ts: "2026-03-19 10:30",
  },
  {
    id: 8,
    type: "deleted",
    user: "admin@campaignos.io",
    target: "Harrison 2024 (archived)",
    detail: "Campaign permanently deleted",
    ts: "2026-03-18 15:00",
  },
];
